name: Unit tests

on:
  push:
  workflow_dispatch:

jobs:

  ut:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -e ".[dev]"

    - name: Run app tests
      run: pytest

    - name: Run vendored library tests
      run: pytest yahoo_fantasy_api/tests

    - name: Lint
      run: ruff check fcc tests
